name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Send info about new change
        run: |
          curl -i -X POST -H 'Content-Type: application/json' -d '{"username": "Github BOT", "text": "New change: "${{ github.event.head_commit.message }}" by: ${{ github.event.pull_request.user.login }}"}' https://chat.dfijolek.pl/hooks/q9dbfeo9dt8axx7ah3z7er371h
        
      - name: Check out the repo
        uses: actions/checkout@v3
    
      #- name: Build the Docker image
      #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        
      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: edamianfijolek/testapi
          #flavor: latest=true
          
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          #tags: ${{ steps.meta.outputs.tags }}
          tags: edamianfijolek/testapi:latest
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: notify success
        if: success()
        run: |
          curl -i -X POST -H 'Content-Type: application/json' -d '{"username": "Github BOT", "text": "Build finished ✅"}' https://chat.dfijolek.pl/hooks/q9dbfeo9dt8axx7ah3z7er371h    
      
      - name: notify failure
        if: failure()
        run: |
          curl -i -X POST -H 'Content-Type: application/json' -d '{"username": "Github BOT", "text": "Build failed ❌"}' https://chat.dfijolek.pl/hooks/q9dbfeo9dt8axx7ah3z7er371h
      


